# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0003_auto_20170324_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='id',
            new_name='user',
        ),
    ]
