# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0004_auto_20170324_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
