# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 02:14
from __future__ import unicode_literals
from clone.models import Listing, User_Profile
from django.db import migrations


def create_a_listing(apps, schema_editor):
    owner = User_Profile.objects.get(user_id=1)
    listing = Listing.objects.create(title="stuff for stuff", category="stuff", city="durham", description="I got stuff, you got stuff", picture_link="www.google.com", owner=owner)
    listing.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0005_listing_title'),
    ]

    operations = [
        migrations.RunPython(create_a_listing)
    ]
