# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0006_auto_20170325_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('sub_cat', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
