# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0009_auto_20170325_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='name',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
