# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:30
from __future__ import unicode_literals
from clone.models import Category
from django.db import migrations


def create_categories(apps, schema_editor):
    category = Category(category='Stuff')
    category.save()
    category = Category(category='Not Stuff')
    category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0010_sub_category_name'),
    ]

    operations = [
        migrations.RunPython(create_categories)
    ]
