# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:51
from __future__ import unicode_literals
from clone.models import Category, Sub_Category
from django.db import migrations


def make_sub_cats(apps, schema_editor):
    sub_cat = Sub_Category(category_id=Category.objects.get(category=stuff), name="hot stuff")


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0011_auto_20170325_1230'),
    ]

    operations = [
    ]
