# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 16:50
from __future__ import unicode_literals
from clone.models import Category, Sub_Category
from django.db import migrations


def make_sub_cats(apps, schema_editor):
    sub_cat = Sub_Category(category_id=Category.objects.get(category='Stuff').id, name="Hot stuff")
    sub_cat.save()
    sub_cat = Sub_Category(category_id=Category.objects.get(category='Stuff').id, name="Cold stuff")
    sub_cat.save()
    sub_cat = Sub_Category(category_id=Category.objects.get(category='Not Stuff').id, name="Not Hot Stuff")
    sub_cat.save()
    sub_cat = Sub_Category(category_id=Category.objects.get(category='Not Stuff').id, name="Not Cold Stuff")
    sub_cat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0012_auto_20170325_1251'),
    ]

    operations = [
        migrations.RunPython(make_sub_cats)
    ]
