# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0013_auto_20170325_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clone.City'),
        ),
    ]
